class Product {
  final String id;
  final String name;
  final String image;
  final double price;
  final String category;
  final String description;
  final double rating;
  final int soldCount;
  final List<String> availableSizes;
  final List<String> availableFlavors;

  Product({
    required this.id,
    required this.name,
    required this.image,
    required this.price,
    required this.category,
    required this.description,
    required this.rating,
    required this.soldCount,
    this.availableSizes = const ["Regular", "Large"],
    this.availableFlavors = const ["Original", "Pedas"],
  });
}

List<Product> dummyProducts = [
  Product(
    id: "1",
    name: "Ayam Geprek",
    image: "https://images.unsplash.com/photo-1626645738196-c2a7c87a8f26?w=400&h=300&fit=crop",
    price: 25000,
    category: "Best Seller",
    description: "Ayam geprek dengan sambal pedas yang mantap, crispy dan juicy!",
    rating: 4.8,
    soldCount: 1250,
    availableSizes: ["Regular", "Large", "Extra Large"],
    availableFlavors: ["Original", "Pedas", "Super Pedas"],
  ),
  Product(
    id: "2",
    name: "Burger Premium",
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&h=300&fit=crop",
    price: 35000,
    category: "Promo",
    description: "Burger dengan daging sapi premium, keju meleleh, dan sayuran segar",
    rating: 4.6,
    soldCount: 890,
    availableSizes: ["Regular", "Large"],
    availableFlavors: ["Original", "Cheese", "Spicy"],
  ),
  Product(
    id: "3",
    name: "Es Teh Manis",
    image: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&h=300&fit=crop",
    price: 8000,
    category: "Minuman",
    description: "Es teh manis segar dengan gula aren asli, perfect untuk menemani makanan",
    rating: 4.5,
    soldCount: 2100,
    availableSizes: ["Regular", "Large"],
    availableFlavors: ["Original", "Lemon", "Mint"],
  ),
  Product(
    id: "4",
    name: "Kopi Susu Gula Aren",
    image: "https://images.unsplash.com/photo-1541167760496-1628856ab772?w=400&h=300&fit=crop",
    price: 18000,
    category: "Minuman",
    description: "Kopi susu dengan gula aren asli, creamy dan tidak terlalu manis",
    rating: 4.7,
    soldCount: 1560,
    availableSizes: ["Regular", "Large"],
    availableFlavors: ["Original", "Vanilla", "Caramel"],
  ),
  Product(
    id: "5",
    name: "Nasi Goreng Spesial",
    image: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=400&h=300&fit=crop",
    price: 22000,
    category: "Best Seller",
    description: "Nasi goreng dengan telur, ayam, udang, dan sayuran segar",
    rating: 4.9,
    soldCount: 980,
    availableSizes: ["Regular", "Large"],
    availableFlavors: ["Original", "Pedas", "Extra Pedas"],
  ),
  Product(
    id: "6",
    name: "Mie Goreng",
    image: "https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=400&h=300&fit=crop",
    price: 20000,
    category: "Best Seller",
    description: "Mie goreng dengan bumbu special, telur, dan sayuran segar",
    rating: 4.7,
    soldCount: 750,
    availableSizes: ["Regular", "Large"],
    availableFlavors: ["Original", "Pedas", "Seafood"],
  ),
  Product(
    id: "7",
    name: "Sate Ayam",
    image: "https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=400&h=300&fit=crop",
    price: 28000,
    category: "Best Seller",
    description: "Sate ayam dengan bumbu kacang yang kental dan pedas",
    rating: 4.8,
    soldCount: 650,
    availableSizes: ["10 tusuk", "15 tusuk", "20 tusuk"],
    availableFlavors: ["Original", "Pedas", "Extra Pedas"],
  ),
  Product(
    id: "8",
    name: "Gado-gado",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&h=300&fit=crop",
    price: 18000,
    category: "Sehat",
    description: "Sayuran segar dengan bumbu kacang yang creamy dan lezat",
    rating: 4.6,
    soldCount: 420,
    availableSizes: ["Regular", "Large"],
    availableFlavors: ["Original", "Pedas"],
  ),
  Product(
    id: "9",
    name: "Es Campur",
    image: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=400&h=300&fit=crop",
    price: 15000,
    category: "Minuman",
    description: "Es campur dengan berbagai buah, jelly, dan sirup yang menyegarkan",
    rating: 4.5,
    soldCount: 680,
    availableSizes: ["Regular", "Large"],
    availableFlavors: ["Original", "Strawberry", "Mangga"],
  ),
  Product(
    id: "10",
    name: "Pisang Goreng",
    image: "https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?w=400&h=300&fit=crop",
    price: 12000,
    category: "Snack",
    description: "Pisang goreng crispy dengan taburan gula dan keju parut",
    rating: 4.4,
    soldCount: 890,
    availableSizes: ["5 pcs", "10 pcs", "15 pcs"],
    availableFlavors: ["Original", "Keju", "Coklat"],
  ),
  Product(
    id: "11",
    name: "Soto Ayam",
    image: "https://images.unsplash.com/photo-1563379091339-03246963c8f9?w=400&h=300&fit=crop",
    price: 25000,
    category: "Best Seller",
    description: "Soto ayam dengan kuah kaldu yang gurih dan pelengkap lengkap",
    rating: 4.8,
    soldCount: 720,
    availableSizes: ["Regular", "Large"],
    availableFlavors: ["Original", "Pedas"],
  ),
  Product(
    id: "12",
    name: "Bakso",
    image: "https://images.unsplash.com/photo-1563379091339-03246963c8f9?w=400&h=300&fit=crop",
    price: 20000,
    category: "Best Seller",
    description: "Bakso sapi dengan kuah kaldu yang gurih dan bakso yang kenyal",
    rating: 4.7,
    soldCount: 580,
    availableSizes: ["5 pcs", "10 pcs", "15 pcs"],
    availableFlavors: ["Original", "Pedas"],
  ),
];
